  xmlcalabash:process("http://www.sgmlguru.org/exist/rest/db/work/system/cosml/xproc/xref-check-cosml.xpl",("-imap=http://www.sgmlguru.org/exist/rest/db/work/system/common/xml/resource-map.xml -istylesheet=http://www.sgmlguru.org/exist/rest/db/work/system/cosml/xslt/link-target-check-multifile.xsl "),("htm=http://www.sgmlguru.org/exist/rest/db/work/system/cosml/out/my-xref-check.htm file-url=http://www.sgmlguru.org/exist/rest/db/work/system/cosml/out/files.xml "))
      
      
      
         
         
         
      
      
      
      
         
         
      
      
      
      
      
      
         

         
         
         
         
         
         
         
         
         
      
      
      
      
         
         
      
   